#pragma once
#include <iostream>
#include <random>

/// code generated by ChatGPT, as this function is weird and not something that
/// I need to understand rn.
class RandomNumberGenerator {
public:
  // Constructor that takes an integer seed
  explicit RandomNumberGenerator(int seed) : gen(seed), dis(-1.0, 1.0) {}

  // Method to generate a random double between -1 and 1
  double generate() {
    return dis(gen);
  }

private:
  std::mt19937 gen; // Mersenne Twister random number generator
  std::uniform_real_distribution<double>
      dis; // Uniform distribution in the range [-1, 1]
};

int main() {
  int seed = 42;

  // Create an instance of RandomNumberGenerator with a seed
  RandomNumberGenerator rng(seed);

  // Generate some random numbers
  std::cout << "Random numbers with seed " << seed << ":\n";
  for (int i = 0; i < 5; ++i) {
    std::cout << rng.generate() << "\n";
  }

  return 0;
}
